version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: app
    volumes:
      - ./src:/var/www
    environment:
      - DB_HOST=db
      - DB_NAME=twitter
      - DB_USER=root
      - DB_PASSWORD=root
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "9000:9000"
    networks:
      - app-network

  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - ./src:/var/www
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_DATABASE: twitter
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    networks:
      - app-network

  listener:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: listener
    command: php /var/www/app/Listeners/TweetListener.php
    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
